# This file will be copyed to build/

all:
	./mt -s THEME1.CNF --stats 

# Build the app directory.
	-mkdir myapp
	-cp gramado.css  myapp/
	-cp gramado.js   myapp/
	-cp index.html   myapp/

#clean:
#


