# This file will be copyed to build/

appName = myapp

all:
#	./gramado -s THEME1.CNF --stats 
	./gramado -s THEME1.CNF --stats --dumpo  

# Build the app directory.
	-mkdir $(appName)
	-cp gramado.css  $(appName)/
	-cp gramado.js   $(appName)/
	-cp index.html   $(appName)/
	-cp output.asm   $(appName)/

#clean:
#


